config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'
  get 'dashboard', to: "users#dashboard" #, as: :dashboard
  get '/users/:id', to: "users#show", as: :user

  get '/selling_orders', to: "orders#selling_orders"
  get '/buying_orders', to: "orders#buying_orders"
  get '/orders/:id', to: "orders#show", as: "order_detail"

  get '/all-requests', to: "requests#list"
  get 'request_offers/:id', to: "requests#offers", as: 'request_offers'
  get '/my_offers', to: "offers#my_offers"

  get '/search', to: "pages#search"

  get 'settings/payment', to: "users#payment", as: 'settings_payment'
  get 'settings/payout', to: "users#payout", as: 'settings_payout'

  get 'gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'

  get '/earnings', to: "users#earnings", as: 'earnings'

  get '/conversations', to: "conversations#list", as: "conversations"
  get '/conversations/:client_id', to: "conversations#show", as: "conversation_detail"

  post "users/edit", to: "users#update"
  put '/orders/:id/complete',  to: "orders#complete", as: 'complete_order'

  post "/offers", to: "offers#create"
  put '/offers/:id/accept', to: 'offers#accept', as: :accept_offer
  put '/offers/:id/reject', to: 'offers#reject', as: :reject_offer

  post '/reviews', to: 'reviews#create'
  post 'users/edit_phone', to: 'users#callback_phone'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: "users#withdraw", as: 'withdraw'

  post 'messages', to: "messages#create"

  post 'comments', to: "comments#create"

  devise_for :users,
             path: '',
             path_names: { sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  get 'pages/home'

  root to: "pages#home"

  mount ActionCable.server => "/cable"

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end

    resources :orders, only: [:create] # POST gigs/:gig_id/orders
  end

  resources :requests

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :avatar
  has_many :gigs

  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :requests
  has_many :offers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  validates :full_name, presence:  true, length: { maximum: 50 }

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      if !user.provider
          user.update(
            uid: auth.uid,
            provider: auth.provider,
            image: auth.info.image
          )
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end

  def hidden_phone
    if self.phone && self.phone.length > 3
      "*" * (self.phone.length - 3) + self.phone.last(3)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    if params[:category]
      @gigs = current_user.gigs.joins(:category).where(categories: { name: params[:category] }).all
    else
      @gigs = current_user.gigs
    end

  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(seller_id: params[:id]).order(created_at: :asc)
  end

  def update
    @user = current_user
    if @user.update(current_user_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Cannot update..."
    end

    redirect_to dashboard_path
  end

  def callback_phone
    path_access_token = "https://graph.accountkit.com/v1.1/access_token?" +
                         "grant_type=authorization_code" +
                         "&code=#{params[:code]}" +
                         "&access_token=AA|#{Rails.application.credentials.facebook_api}|#{Rails.application.credentials.facebook_kit_secret}"

    response = Net::HTTP.get(URI.parse(path_access_token))
    response = JSON.parse(response)

    if response['access_token']
      path_get_data = "https://graph.accountkit.com/v1.1/me?access_token=#{response['access_token']}"


      response = Net::HTTP.get(URI.parse(path_get_data))
      response = JSON.parse(response)

      if response['phone']['number']
        current_user.update(phone: response['phone']['number'])

        return render json: { success: true }
      end
    end

    return render json: { success: false }
  end

  def update_payment
    unless current_user.stripe_id
      customer = Stripe::Customer.create(
        email: current_user.email,
        source: params[:stripeToken]
      )
    else
      customer = Stripe::Customer.update(
        current_user.stripe_id,
        source: params[:stripeToken]
      )
    end

    if current_user.update(
      stripe_id: customer.id,
      stripe_last_4: customer.sources.data.first['last4']
    )

      flash[:notice] = "New card is saved"
    else
      flash[:alert] = "Invalid card"
    end

    redirect_to request.referrer

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to request.referrer
  end

  def update_payout
    if current_user.update(paypal: params[:paypal])
      flash[:notice] = "Update payout successfully"
    else
      flash[:alert] = "Something went wrong"
    end

    redirect_to request.referrer
  end

  def earnings
    @net_income = (Transaction.where("seller_id = ?", current_user.id).sum(:amount) / 1.1).round(2)

    @with_drawn = Transaction.where(
      'buyer_id = ? AND status = ? AND transaction_type = ?',
      current_user.id,
      Transaction.statuses[:approved],
      Transaction.transaction_types[:withdraw]
    ).sum(:amount)

    @pending = Transaction.where(
      'buyer_id = ? AND status = ? AND transaction_type = ?',
      current_user.id,
      Transaction.statuses[:pending],
      Transaction.transaction_types[:withdraw]
    ).sum(:amount)

    @purchased = Transaction.where(
      'buyer_id = ? AND source_type = ? AND transaction_type = ?',
      current_user.id,
      Transaction.source_types[:system],
      Transaction.transaction_types[:trans]
    ).sum(:amount)

    @withdrawable = current_user.wallet

    @transactions = Transaction.where(
      "seller_id = ? OR (buyer_id = ? AND source_type = ?)",
      current_user.id,
      current_user.id,
      Transaction.source_types[:system]
    ).page(params[:page])

  end

  def withdraw
    amount = params[:amount].to_i

    # Only 1 withdraw request at the same time
    is_pending_withraw = Transaction.exists?(
      buyer_id: current_user.id,
      status: Transaction.statuses[:pending],
      transaction_type: Transaction.transaction_types[:withdraw])

    if amount <= 0
      flash[:alert] = "Invalid amound"
    elsif amount > current_user.wallet
      flash[:alert] = "You're asking for more than you have"
    elsif is_pending_withraw
      flash[:alert] = "You currently have a pending withdraw request"
    else
      transaction = Transaction.new
      transaction.status = Transaction.statuses[:pending]
      transaction.transaction_type = Transaction.transaction_types[:withdraw]
      transaction.source_type = Transaction.source_types[:system]
      transaction.buyer = current_user
      transaction.amount = amount

      if transaction.save
        flash[:notice] = "Your withdraw request was created"
      else
        flash[:alert] = "Cannot create your withdrawal request"
      end
    end

    redirect_to request.referrer
  end

  private

  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    if user.avatar.attached?
      url_for(user.avatar)
    elsif user.image?
      user.image
    else
      ActionController::Base.helpers.asset_path('icon_default_avatar.png')
    end
  end
end

app/views/users/dashboard.html.erb
<!-- HTTPS required. HTTP will give a 403 forbidden response -->
<script src="https://sdk.accountkit.com/en_US/sdk.js"></script>


<section class="section">
  <div class="container">
    <div class="columns">

      <!-- LEFT SIDE -->
      <div class="column is-one-third">
        <div class="columns is-multiline">

          <!-- Top Card -->
          <div class="column is-full">
            <div class="card">

              <!-- Avatar -->
              <div class="card-content is-horizontal-center is-flex">
                <figure class="image is-128x128">
                  <%= image_tag avatar_url(current_user), class: 'is-rounded' %>
                </figure>
              </div>

              <div class="card-content">

                <!-- Upload Button -->
                <div class="content has-text-centered">
                  <p class="title is-5"><%= current_user.full_name %></p>

                  <%= form_for :user, url: users_edit_url(current_user), action: :update, method: :post do |f| %>
                    <div class="file">
                      <label for="" class="button is-primary is-outlined is-fullwidth">
                        <%= f.file_field :avatar, class: 'file-input', onchange: "this.form.submit();" %>
                        <i class="fa fa-upload"></i>&nbsp; &nbsp; &nbsp; Upload Avatar
                      </label>
                    </div>
                  <% end %>
                </div>
                <hr class="h-10">

                <!-- Member -->
                <article class="media">
                  <div class="media-content">
                    Member since
                  </div>
                  <div class="media-right">
                    <strong><%= current_user.created_at.strftime('%b %Y') %></strong>
                  </div>
                </article>
                <hr class="h-10">

                <!-- From -->
                <article>
                  <div class="media">
                    <div class="media-content">From</div>
                    <div class="media-right">
                      <strong><%= current_user.from %></strong>
                      <i class="toggle fa fa-edit" aria-controls="user-from"></i>
                    </div>
                  </div>

                  <div class="content">
                    <%= form_for :user, url: users_edit_url(current_user), action: :update, method: :post, html: {id: 'user-from', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_field :from, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>

                      <a class="toggle button is-light" aria-controls="user-from">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Online Status -->
                <article>
                  <div class="media">
                    <div class="media-content">Online Status</div>
                    <div class="media-right">
                      <strong><%= current_user.status ? 'Online' : 'Offline' %></strong>
                      <i class="toggle fa fa-edit" aria-controls="user-status"></i>
                    </div>
                  </div>


                  <div class="content">
                    <%= form_for :user, url: users_edit_url(current_user), action: :update, method: :post, html: {id: 'user-status', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.select(:status, options_for_select({"Online" => "true", "Offline" => "false"}, current_user ? "#{current_user.status}" : "false"), {}, { class: "select is-fullwidth"} ) %>
                      </div>

                      <a class="toggle button is-light" aria-controls="user-status">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>

              </div>
            </div>
          </div>

          <!-- Bottom Card -->
          <div class="column is-full">
            <div class="card">
              <div class="card-content">

                <!-- About -->
                <article>
                  <div class="media">
                    <div class="media-content">
                      <p>
                        <strong>About yourself</strong>
                      </p>
                      <br/>
                      <%= current_user.about %>
                    </div>

                    <div class="media-right">
                      <i class="toggle fa fa-edit" aria-controls="user-about"></i>
                    </div>
                  </div>

                  <div class="content">
                    <%= form_for :user, url: users_edit_url(current_user), action: :update, method: :post, html: {id: 'user-about', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_area :about, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>

                      <a class="toggle button is-light" aria-controls="user-about">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Languages -->
                <article>
                  <div class="media">
                    <div class="media-content">
                      <p>
                        <strong>Language</strong>
                      </p>
                      <br/>
                      <%= current_user.language %>
                    </div>

                    <div class="media-right">
                      <i class="toggle fa fa-edit" aria-controls="user-language"></i>
                    </div>
                  </div>

                  <div class="content">
                    <%= form_for :user, url: users_edit_url(current_user), action: :update, method: :post, html: {id: 'user-language', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_area :language, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>

                      <a class="toggle button is-light" aria-controls="user-language">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Linked Account -->
                <article class="media">
                  <div class="content">
                    <p>
                      <strong>Linked Account</strong>
                    </p>

                    <p>
                      <% if current_user.uid %>
                        <span class="has-text-success">Facebook verified</span>
                      <% else %>
                        <%= link_to 'Connect to Facebook', user_facebook_omniauth_authorize_path, class: 'has-text-danger' %>
                      <% end %>
                    </p>
                  </div>
                </article>

                <!-- Mobile number -->
                <article>
                  <div class="media">
                    <div class="media-content">
                      <p>
                        <strong>Mobile Number</strong>
                      </p>
                      <br/>
                      <%= current_user.hidden_phone%>
                    </div>

                    <div class="media-right">
                      <i class="toggle fa fa-edit" aria-controls="user-phone"></i>
                    </div>
                  </div>

                  <div class="content">
                    <%= form_for :user, url: users_edit_url(current_user), action: :update, method: :post, html: {id: 'user-phone', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_field :phone, autofocus: true, autocomplete: 'form', class: 'input', id: "phone_number" %>
                      </div>

                      <a class="toggle button is-light" aria-controls="user-phone">Cancel</a>
                      <%= link_to "Add & Verify", "javascript:verifyPhone()", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
              </div>
            </div>
          </div>

        </div>
      </div>

      <!-- RIGHT SIDE -->
      <div class="column">
        <div class="columns is-multiline">

          <!-- Create New Gig -->
          <div class="column is-one-third has-text-centered">
            <%= link_to new_gig_path do %>
              <div class="card">

                <div class="card-image card-content is-horizontal-center is-flex ">
                  <figure class="image is-128x128 ">
                    <%= image_tag 'icon_add.png' %>
                  </figure>
                </div>

                <div class="card-content">
                  <strong>Create a new gig</strong>
                </div>
              </div>
            <% end %>

          </div>



          <!-- Sample Gig -->
          <% @gigs.each do |gig| %>
            <div class="column is-one-third">
              <div class="card">

                <div class="card-image">
                  <%= link_to edit_gig_path(gig) do %>
                    <figure class="image is-4by3">
                      <%= image_tag gig_cover(gig) %>
                    </figure>
                  <% end %>
                </div>

                <div class="card-content p-t-5 p-b-5">
                  <p class="subtitle is-6 m-b-5">
                    <%= link_to gig.title, gig_path(gig) %>
                  </p>
                  <span class="star-review">
                    <i class="fa fa-star"></i>
                    <%= gig.average_rating %>

                    <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
                  </span>
                </div>

                <% pricing = basic_pricing gig %>
                <footer class="card-footer">
                  <a class="has-text-danger is-block card-footer-item has-text-right">

                    <% if pricing %>
                      <span class="small-title">STARTING AT</span>
                      <strong>$<%= pricing.price %></strong>
                    <% else %>
                      <span class="small-title has-text-dark">NO PRICING YET</span>
                    <% end %>
                  </a>
                </footer>

              </div>
            </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</section>




<!-- HTTPS required. HTTP will give a 403 forbidden response -->
<script src="https://sdk.accountkit.com/en_US/sdk.js"></script>

<script>
  // initialize Account Kit with CSRF protection
  AccountKit_OnInteractive = function(){
    AccountKit.init(
      {
        appId:"<%= Rails.application.credentials.facebook_api %>",
        state:"freelancer",
        version:"v1.1",
        debug: true
      }
    );
  };

  // login callback
  function loginCallback(response) {
    if (response.status === "PARTIALLY_AUTHENTICATED") {
      var code = response.code;
      $.ajax({
        type: "POST",
        url: "/users/edit_phone",
        data: { code: code },
        success: (data) => {
          if (data.success) {
            showNotification('success', 'Update phone number successfully');
            location.reload()
          } else {
            showNotification('error', 'Invalid phone number');
          }
        },
        error: (data) => {
          showNotification('error', 'Invalid phone number');
        }
      });

      // Send code to server to exchange for access token
    }
    else if (response.status === "NOT_AUTHENTICATED") {
      // handle authentication failure
      showNotification('error', 'Not Authenticate');
    }
    else if (response.status === "BAD_PARAMS") {
      // handle bad parameters
      showNotification('error', 'Not Authenticate');
    }
  }

  // phone form submission handler
  function verifyPhone() {
    var phoneNumber = document.getElementById("phone_number").value;
    AccountKit.login(
      'PHONE',
      {phoneNumber: phoneNumber}, // will use default values if not specified
      loginCallback
    );
  }

  function showNotification(type, message) {
    new Noty({
      type: type,
      layout: "topRight",
      timeout: 2000,
      theme: 'sunset',
      text: message
    })
  }

</script>

app/views/users/payout.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8-tablet is-6-desktop is-6-widescreen">
        <p class="title has-text-centered">Payout Method</p>

        <%= form_with url: update_payout_path, local: true do |f| %>
          <div class="field">
            <%= f.text_field :paypal,
                             value: current_user.paypal,
                             placeholder: 'Your Paypal email',
                             class: 'input'%>
          </div>
          <div class="field is-grouped is-grouped-centered">
            <%= f.submit "Save", class: 'button is-primary is-fullwidth' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">

      <!-- LEFT SIDE -->
      <div class="column is-one-third">
        <div class="columns is-multiline">

          <!-- Top Card -->
          <div class="column is-full">
            <div class="card">

              <!-- Avatar -->
              <div class="card-content is-horizontal-center is-flex">
                <figure class="image is-128x128">
                  <%= image_tag avatar_url(@user), class: 'is-rounded' %>
                </figure>
              </div>

              <div class="card-content">

                <!-- Upload Button -->
                <div class="content has-text-centered">
                  <p class="title is-5">
                    <%= @user.full_name %>
                    <%= link_to edit_user_registration_path do %>
                      <i class="fa fa-pencil is-size-7" style="margin-left: 5px;"></i>
                    <% end %>
                  </p>

                  <% if current_user.id != @user.id %>
                    <a class="button is-black is-outlined is-fullwidth toggle-contact">Contact Me</a>
                  <% end %>
                </div>
                <hr class="h-10">

                <!-- Member -->
                <article class="media">
                  <div class="media-content">
                    Member since
                  </div>
                  <div class="media-right">
                    <strong><%= @user.created_at.strftime('%b %Y') %></strong>
                  </div>
                </article>
                <hr class="h-10">

                <!-- From -->
                <article class="media">
                  <div class="media-content">From</div>
                  <div class="media-right">
                    <strong><%= @user.from %></strong>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Online Status -->
                <article class="media">
                  <div class="media-content">Online Status</div>
                  <div class="media-right">
                    <strong><%= @user.status ? 'Online' : 'Offline' %></strong>
                  </div>
                </article>

              </div>
            </div>
          </div>

          <!-- Bottom Card -->
          <div class="column is-full">
            <div class="card">
              <div class="card-content">

                <!-- About -->
                <article class="media">
                  <div class="media-content">
                    <p>
                      <strong>About yourself</strong>
                    </p>
                    <br/>
                    <%= @user.about %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Languages -->
                <article  class="media">
                  <div class="media-content">
                    <p>
                      <strong>Language</strong>
                    </p>
                    <br/>
                    <%= @user.language %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Linked Account -->
                <article class="media">
                  <div class="content">
                    <p>
                      <strong>Linked Account</strong>
                    </p>

                    <p>
                      <% if @user.uid %>
                        <span class="has-text-success">Facebook verified</span>
                      <% else %>
                        <span class="has-text-danger">Facebook unverified</span>
                      <% end %>
                    </p>
                  </div>
                </article>


                <!-- Mobile Number -->
                <article class="media">
                  <div class="content">
                    <p>
                      <strong>Mobile Number</strong>
                    </p>

                    <p>
                      <% if @user.phone %>
                        <span class="has-text-success">Mobile # verified</span>
                      <% else %>
                        <span class="has-text-danger">Mobile # unverified</span>
                      <% end %>
                    </p>
                  </div>
                </article>

              </div>
            </div>
          </div>

        </div>
      </div>

      <!-- RIGHT SIDE -->
      <div class="column">
        <div class="columns is-multiline">
          <!-- Sample Gig -->
          <% @user.gigs.each do |gig| %>
            <div class="column is-one-third">
              <div class="card">

                <div class="card-image">
                  <%= link_to edit_gig_path(gig) do %>
                    <figure class="image is-4by3">
                      <%= image_tag gig_cover(gig) %>
                    </figure>
                  <% end %>
                </div>

                <div class="card-content p-t-5 p-b-5">
                  <p class="subtitle is-6 m-b-5">
                    <%= link_to gig.title, gig_path(gig) %>
                  </p>
                  <span class="star-review">
                      <i class="fa fa-star"></i>
                    <%= gig.average_rating %>

                    <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
                    </span>
                </div>

                <% pricing = basic_pricing gig %>
                <footer class="card-footer">
                  <a class="has-text-danger is-block card-footer-item has-text-right">

                    <% if pricing %>
                      <span class="small-title">STARTING AT</span>
                      <strong>$<%= pricing.price %></strong>
                    <% else %>
                      <span class="small-title has-text-dark">NO PRICING YET</span>
                    <% end %>
                  </a>
                </footer>

              </div>
            </div>
          <% end %>
        </div>

        <div class="card">
          <div class="card-header">
            <div class="card-header-title"> Latest Reviews </div>
          </div>

          <div class="card-content">
            <!-- Sample Reviews -->
            <% @reviews.each do |review| %>
              <article class="media">
                <figure class="media-left">
                  <p class="image is-64x64">
                    <%= image_tag avatar_url(review.buyer), class: 'is-rounded' %>
                  </p>
                </figure>
                <div class="media-content">
                  <div class="content">
                    <p>
                      <strong><%= review.buyer.full_name %></strong><br/>
                      <%= review.review %>
                    </p>

                    <small><%= time_ago_in_words(review.created_at) %></small>
                  </div>
                </div>

                <div class="media-right">
                <span class="star-review">
                  <i class="fa fa-star"> <%= review.stars %></i>
                </span>
                </div>
              </article>
            <% end %>

          </div>
        </div>
      </div>

    </div>
  </div>
</section>

<div class="modal" id="contact-form">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Send a Message</p>
      <button class="delete toggle-contact" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <div class="columns">
        <div class="column is-one-third">
          <div class="card" st>
            <div class="card-content is-horizontal-center is-flex">
              <figure class="image is-128x128">
                <%= image_tag avatar_url(@user), class: 'is-rounded' %>
              </figure>
            </div>
            <div class="card-content">
              <hr>
              <strong>Please include:</strong>
              <ul class="is-size-7" style="list-style:initial">
                <li>Project description</li>
                <li>Specific instructions</li>
                <li>Relevant files</li>
                <li>Your budget</li>
              </ul>
            </div>
          </div>
        </div>

        <div class="column">

          <%= form_with model: Message.new do |f| %>
            <%= f.hidden_field :receiver_id, value: @user.id %>

            <div class="card-content">
              <div class="field">
                <div class="control">
                  <%= f.text_area :content, class: 'textarea' %>
                </div>
              </div>

              <%= f.submit "Send", class: "button is-danger is-pulled-right" %>
            </div>
          <% end %>

        </div>
      </div>
    </section>
  </div>
</div>

<script>
  var toggle_modals = $('.toggle-contact');
  if (toggle_modals) {
    toggle_modals.on('click', function(event) {
      event.stopPropagation();
      event.preventDefault();
      var form = document.getElementById('contact-form');
      form.classList.toggle('is-active');
    });
  }
</script>