config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'
  get 'dashboard', to: "users#dashboard" #, as: :dashboard
  get '/users/:id', to: "users#show", as: :user

  get '/selling_orders', to: "orders#selling_orders"
  get '/buying_orders', to: "orders#buying_orders"
  get '/orders/:id', to: "orders#show", as: "order_detail"

  get '/all-requests', to: "requests#list"
  get 'request_offers/:id', to: "requests#offers", as: 'request_offers'
  get '/my_offers', to: "offers#my_offers"

  get '/search', to: "pages#search"

  get 'settings/payment', to: "users#payment", as: 'settings_payment'
  get 'settings/payout', to: "users#payout", as: 'settings_payout'

  get 'gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'

  get '/earnings', to: "users#earnings", as: 'earnings'

  get '/conversations', to: "conversations#list", as: "conversations"
  get '/conversations/:client_id', to: "conversations#show", as: "conversation_detail"

  post "users/edit", to: "users#update"
  put '/orders/:id/complete',  to: "orders#complete", as: 'complete_order'

  post "/offers", to: "offers#create"
  put '/offers/:id/accept', to: 'offers#accept', as: :accept_offer
  put '/offers/:id/reject', to: 'offers#reject', as: :reject_offer

  post '/reviews', to: 'reviews#create'
  post 'users/edit_phone', to: 'users#callback_phone'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: "users#withdraw", as: 'withdraw'

  post 'messages', to: "messages#create"

  post 'comments', to: "comments#create"

  devise_for :users,
             path: '',
             path_names: { sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  get 'pages/home'

  root to: "pages#home"

  mount ActionCable.server => "/cable"

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end

    resources :orders, only: [:create] # POST gigs/:gig_id/orders
  end

  resources :requests

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :gigs
  has_many :requests
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  def last_message
    message = Message.where(conversation_id: self.id).last

    if message.present?
      return message
    else
      return Message.new(updated_at: Time.now)
    end
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :pricings, dependent: :destroy
  has_many :orders#, dependent: :destroy
  has_many :reviews#, dependent: :destroy

  has_many_attached :photos
  has_rich_text :description

  accepts_nested_attributes_for :pricings
  validates :title, presence: { message: "Can't be blank" }

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:stars).round(1)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :request
  belongs_to :user

  has_many :reviews

  enum status: [:pending, :accepted, :rejected]
  validates :amount, :days, numericality: { only_integer: true, message: "Must be a number" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :gig, required: false
  belongs_to :request, required: false

  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  enum status: [:inprogress, :completed]
end

app/models/pricing.rb
class Pricing < ApplicationRecord
  belongs_to :gig

  enum pricing_type: [:basic, :standard, :premium]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :attachment_file
  has_many :offers, dependent: :delete_all
  has_many :orders

  validates :title, presence: { message: "cannot be empty" }
  validates :description, presence: { mesasge: "cannot be empty" }
  validates :delivery, numericality: { only_integer: true, mesasge: "must be a number" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :order
  belongs_to :gig, required: false
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User", optional: true
  belongs_to :gig, optional: true
  belongs_to :request, optional: true

  enum status: %i[approved pending rejected]
  enum transaction_type: %i[trans withdraw]
  enum source_type: %i[system stripe]

end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :avatar
  has_many :gigs

  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :requests
  has_many :offers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  validates :full_name, presence:  true, length: { maximum: 50 }

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      if !user.provider
          user.update(
            uid: auth.uid,
            provider: auth.provider,
            image: auth.info.image
          )
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end

  def hidden_phone
    if self.phone && self.phone.length > 3
      "*" * (self.phone.length - 3) + self.phone.last(3)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
  def gig_cover gig
    if gig.photos.attached?
      url_for(gig.photos[0])
    else
      ActionController::Base.helpers.asset_path('icon_default_image.png')
    end
  end

  def basic_pricing gig
    gig.pricings.find { |p| p.pricing_type == "basic" }
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    if user.avatar.attached?
      url_for(user.avatar)
    elsif user.image?
      user.image
    else
      ActionController::Base.helpers.asset_path('icon_default_avatar.png')
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/dashboard/index.html.erb
<div class="main-content-area">
  <div class="main-content-container">
    <div class="main-content">
      <div class="row">

        <div class="col-md-3 bg-primary">
          <div class="card text-white text-center">
            <h1><%= @user_count %></h1>
            <p>Users</p>
          </div>
        </div>


        <div class="col-md-3 bg-warning">
          <div class="card text-white text-center">
            <h1><%= @gig_count %></h1>
            <p>Gigs</p>
          </div>
        </div>

        <div class="col-md-3 bg-success">
          <div class="card text-white text-center">
            <h1><%= @order_count %></h1>
            <p>Orders</p>
          </div>
        </div>

        <div class="col-md-3 bg-info">
          <div class="card text-white text-center">
            <h1><%= @category_count %></h1>
            <p>Categories</p>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fiverr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <script src="https://js.stripe.com/v3/"></script>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/noty' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
  <div class="container">
    <div class="navbar">
      <% @categories.each do |category| %>
        <%= link_to "#{category.name}", search_path(category: category.id), class: "navbar-item"%>
      <% end %>
    </div>
  </div>

</nav>

app/views/shared/_gigs.html.erb
<!-- Sample Gig -->
<% @gigs.each do |gig| %>
  <div class="column is-one-third">
    <div class="card">

      <div class="card-image">
        <%= link_to gig_path(gig) do %>
          <figure class="image is-4by3">
            <%= image_tag gig_cover(gig) %>
          </figure>
        <% end %>
      </div>

      <div class="card-content p-t-5 p-b-5">
        <p class="subtitle is-6 m-b-5">
          <%= link_to gig.title.truncate(20), gig_path(gig) %>
        </p>
        <span class="star-review">
                      <i class="fa fa-star"></i>
          <%= gig.average_rating %>

          <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
                    </span>
      </div>

      <footer class="card-footer">
        <span class="card-footer-item">
          <%= link_to user_path(gig.user) do %>
            <figure class="image is-32x32">
              <%= image_tag avatar_url(gig.user), class: 'is-rounded' %>
            </figure>
          <% end %>
        </span>

        <a class="has-text-danger is-block card-footer-item has-text-right">
          <span class="small-title">STARTING AT</span>
          <strong>$<%= gig.price %></strong>
        </a>
      </footer>

    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <h1 class="title is-4">Fiverr</h1>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">

    <div class="navbar-start">
      <div class="navbar-start">
        <div class="navbar-item">

          <div class="<%= 'is-hidden' if current_page?(root_path) %>">
            <%= form_tag search_path, method: :get, class: "field has-addons" do %>
              <div class="control has-icons-left">
            <span class="icon is-small is-left">
              <i class="fa fa-search"></i>
            </span>
                <%= text_field_tag 'q', nil, class: 'input', placeholder: "Try 'logo design'" %>
              </div>
              <div class="control">
                <button class="button is-danger" type="submit">
                  Search
                </button>
              </div>
            <% end %>
          </div>

        </div>
      </div>
    </div>

    <div class="navbar-end">
      <%= link_to "Post Gig", new_gig_path, class: 'navbar-item' %>
      <%= link_to "Browse Gigs", search_path, class: 'navbar-item' %>

      <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <figure class="image is-24x24 avatar <%= current_user.status ? 'online' : 'offline' %>">
              <%= image_tag avatar_url(current_user), class: "is-rounded" %>
            </figure>
            &nbsp;<%= current_user.full_name %>
          </a>

          <div class="navbar-dropdown">
            <%= link_to "Profile", user_path(current_user), class: 'navbar-item' %>
            <%= link_to 'Dashboard', dashboard_path, class: 'navbar-item' %>

            <hr class="navbar-divider">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-item' %>
          </div>
        </div>
      <% else %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to "Sign up", new_user_registration_path, class: "button is-primary" %>
            <%= link_to "Sign in", new_user_session_path, class: "button is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

<% if current_user && !current_page?(search_path) && !current_page?(root_path) %>
  <nav class="navbar has-shadow" style="z-index: 5;">
    <div class="container">
      <div class="navbar-menu">
        <div class="navbar-start">
          <%= link_to 'Dashboard', dashboard_path, class: 'navbar-item' %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Selling
            </a>

            <div class="navbar-dropdown">
              <%= link_to 'Create New Gig', new_gig_path, class: 'navbar-item' %>
            </div>
          </div>


          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Buying
            </a>

            <div class="navbar-dropdown">
              <%= link_to "Post Request", new_request_path, class: 'navbar-item' %>
              <%= link_to "Manage Requests", requests_path, class: 'navbar-item' %>
            </div>
          </div>


          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Buyer Requests
            </a>

            <div class="navbar-dropdown">
              <%= link_to "Active Requests", all_requests_path, class: 'navbar-item' %>
              <%= link_to "Offer Sent", my_offers_path, class: 'navbar-item' %>
            </div>
          </div>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Orders
            </a>

            <div class="navbar-dropdown">
              <%= link_to "Selling Orders", selling_orders_path, class: 'navbar-item'%>
              <%= link_to "Buying Orders", buying_orders_path, class: 'navbar-item'%>
            </div>
          </div>

          <%= link_to 'Earnings', earnings_path, class: 'navbar-item' %>
          <%= link_to 'Messages', conversations_path, class: 'navbar-item' %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Settings
            </a>

            <div class="navbar-dropdown">
              <%= link_to "Payment Method", settings_payment_path, class: 'navbar-item'%>
              <%= link_to "Payout Method", settings_payout_path, class: 'navbar-item'%>
            </div>
          </div>
        </div>

        <% if params[:controller] == 'users' && params[:action] == 'dashboard' %>
          <div class="navbar-end">
            <div class="navbar-item">

              <div class="select">
                <select onchange="categorySelected(this)">
                  <option value="">Select Category</option>
                  <% Category.all.each do |category| %>


                      <%= link_to dashboard_path(category: category.name), class: "navbar-item" do %>
                        <option <%= 'selected' if category.name == params[:category] %>> <%= category.name %>  </option>
                      <% end %>


                  <% end %>
                </select>
              </div>

            </div>
          </div>
         <% end %>

      </div>
    </div>
  </nav>
<% end %>

<script>
  categorySelected = function(selection) {
    if(selection.value) {
      window.location.href = "<%= dashboard_path %>" + "?category=" + selection.value;
    } else {
      window.location.href = "<%= dashboard_path %>";
    }

  };

  $(document).ready(function() {

    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

    });
  });
</script>

app/views/shared/_noty.html.erb
<% unless flash.empty? %>
  <% flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
    <script>
      new Noty({
        type: '<%= type %>',
        layout: 'topRight',
        timeout: 1500,
        theme: 'sunset',
        text: '<%= value %>'
      }).show();
    </script>
  <% end %>
<% end %>