config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'
  get 'dashboard', to: "users#dashboard" #, as: :dashboard
  get '/users/:id', to: "users#show", as: :user

  get '/selling_orders', to: "orders#selling_orders"
  get '/buying_orders', to: "orders#buying_orders"
  get '/orders/:id', to: "orders#show", as: "order_detail"

  get '/all-requests', to: "requests#list"
  get 'request_offers/:id', to: "requests#offers", as: 'request_offers'
  get '/my_offers', to: "offers#my_offers"

  get '/search', to: "pages#search"

  get 'settings/payment', to: "users#payment", as: 'settings_payment'
  get 'settings/payout', to: "users#payout", as: 'settings_payout'

  get 'gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'

  get '/earnings', to: "users#earnings", as: 'earnings'

  get '/conversations', to: "conversations#list", as: "conversations"
  get '/conversations/:client_id', to: "conversations#show", as: "conversation_detail"

  post "users/edit", to: "users#update"
  put '/orders/:id/complete',  to: "orders#complete", as: 'complete_order'

  post "/offers", to: "offers#create"
  put '/offers/:id/accept', to: 'offers#accept', as: :accept_offer
  put '/offers/:id/reject', to: 'offers#reject', as: :reject_offer

  post '/reviews', to: 'reviews#create'
  post 'users/edit_phone', to: 'users#callback_phone'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: "users#withdraw", as: 'withdraw'

  post 'messages', to: "messages#create"

  post 'comments', to: "comments#create"

  devise_for :users,
             path: '',
             path_names: { sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  get 'pages/home'

  root to: "pages#home"

  mount ActionCable.server => "/cable"

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end

    resources :orders, only: [:create] # POST gigs/:gig_id/orders
  end

  resources :requests

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :gig, required: false
  belongs_to :request, required: false

  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  enum status: [:inprogress, :completed]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, only: :show

  def create
    gig = Gig.find(params[:gig_id])
    pricing = gig.pricings.find_by(pricing_type: params[:pricing_type])

    if (pricing && !gig.has_single_pricing) || (pricing && pricing.basic? && gig.has_single_pricing)
      if charge(gig, pricing)
        return redirect_to buying_orders_path
      end
    else
      flash[:alert] = "Price is incorrect"
    end

    return redirect_to request.referrer
  end

  def selling_orders
    @orders = current_user.selling_orders
  end

  def buying_orders
    @orders = current_user.buying_orders
  end

  def complete
    @order = Order.find(params[:id])

    if !@order.completed?
      if @order.completed! # @order.update(status: 1)
        flash[:notice] = "Saved..."
      else
        flash[:alert] = "Something went wrong..."
      end

      redirect_to request.referrer
    end
  end

  def show
    @order = Order.find(params[:id])
    @gig = @order.gig_id ? Gig.find(@order.gig_id) : nil
    @request = @order.request_id ? Request.find(@order.request_id) : nil

    @comments = Comment.where(order_id: params[:id])
  end

  private

  def authorize_user
    redirect_to dashboard_path,
                alert: "You don't have permission" unless Order.where("id = ? AND (seller_id = ? OR buyer_id = ?)",
                                                                      params[:id],
                                                                      current_user.id,
                                                                      current_user.id)
  end

  def charge(gig, pricing)
    order = gig.orders.new
    order.due_date = Date.today() + pricing.delivery_time.days
    order.title = gig.title
    order.seller_name = gig.user.full_name
    order.seller_id = gig.user.id

    order.buyer_name = current_user.full_name
    order.buyer_id = current_user.id

    amount = pricing.price * 1.1

    order.amount = amount

    if params[:payment].blank?
      flash[:alert] = "No payment selected"
      return false
    elsif params[:payment] == "system"
      if amount > current_user.wallet
        flash[:alert] = "Not enough money"
        return false
      else
        # We need to rollback transactions if there's any fail transaction
        ActiveRecord::Base.transaction do

          # return error so ActionRecor transaction will rollback every transaction here
          # Without !, the active record query return false only instead of raising error

          current_user.update!(wallet: current_user.wallet - amount)

          gig.user.update!(wallet: gig.user.wallet + pricing.price)

          Transaction.create!(
            status: Transaction.statuses[:approved],
            transaction_type: Transaction.transaction_types[:trans],
            source_type: Transaction.source_types[:system],
            buyer: current_user,
            seller: gig.user,
            amount: amount,
            gig: gig
          )

          order.save
        end

        flash[:notice] = "Your order is created successfully"
        return true
      end
    else
      charge = Stripe::Charge.create(
        amount: (amount * 100).to_i, # to cents
        currency: 'usd',
        customer: current_user.stripe_id,
        source: params[:payment]
      )

      if charge.paid
        # We need to rollback transactions if there's any fail transaction
        ActiveRecord::Base.transaction do
          gig.user.update!(wallet: gig.user.wallet + pricing.price)

          # return error so ActionRecor transaction will rollback every transaction here
          # Without !, the active record query return false only instead of raising error
          Transaction.create!(
            status: Transaction.statuses[:approved],
            transaction_type: Transaction.transaction_types[:trans],
            source_type: Transaction.source_types[:stripe],
            buyer: current_user,
            seller: gig.user,
            amount: amount,
            gig: gig
          )

          order.save
        end

        flash[:notice] = "Your order is created successfully"
        return true
      end

      flash[:alert] = "Invalid card"
      return false
    end
  rescue ActiveRecord::RecordInvalid # Raised when transaction fails
    flash[:alert] = "Something went wrong"
    return false
  end
end

app/views/orders/_comment.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= image_tag avatar_url(comment.user), class: 'is-rounded' %>
    </p>
  </figure>

  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= comment.user.full_name %></strong>
        <br>

        <small class="is-pulled-right">
          <%= time_ago_in_words(comment.created_at) %>
        </small>

        <%= comment.content %>
        <br>
      </p>
    </div>
  </div>
</article>

app/views/orders/buying_orders.html.erb
<section class="section">
  <div class="container">
    <p class="title">Manage Buying Orders</p>

    <table class="table is-fullwidth">
      <thead>
      <tr>
        <th>Date</th>
        <th>Seller Name</th>
        <th>Title</th>
        <th>Due Date</th>
        <th>Amount</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
      </thead>

      <tbody>
      <% if @orders.blank? %>
        <tr>
          <td colspan="7" class="has-text-centered"><h3>Nothing to show</h3></td>
        </tr>
      <% end %>

      <% @orders.each do |order| %>
        <tr>
          <td><%= order.created_at.strftime('%d %b %Y') %></td>
          <td><%= order.seller_name %></td>
          <td>
            <%= link_to order.title, gig_path(order.gig) if order.gig.present? %>
            <%= link_to order.title, request_path(order.request) if order.request.present? %>
          </td>
          <td><%= order.due_date.strftime('%d %b %Y') %></td>
          <td>$<%= order.amount %></td>
          <td>
              <span class="tag <%= 'is-warning' if order.inprogress? %> <%= 'is-success' if order.completed? %>">
                <%= order.status.capitalize %>
              </span>

          </td>
          <td>
            <%= link_to "View", order_detail_path(order), class: "button is-small is-outlined" %>

            <% if order.completed? %>
              <a href="" class="button is-small is-outlined is-danger toggle-modal" aria-control="<%= order.id %>">
                Rating
              </a>

              <div class="modal" id="<%= order.id %>">
                <div class="modal-background"></div>
                <div class="modal-content">
                  <div class="box">
                    <%= form_for Review.new do |f| %>
                      <%= f.hidden_field :order_id, value: order.id %>
                      <div class="field">
                        <div id="star_<%= order.id %>"></div>
                      </div>
                      <div class="field">
                        <%= f.text_area :review, class: "textarea" %>
                      </div>
                      <a href="" class="toggle-modal button is-light" aria-control="<%= order.id %>">Cancel</a>
                      <%= f.submit "Add Review", class: "button is-danger"%>
                    <% end %>
                  </div>
                </div>
              </div>
            <% else %>
              <%= link_to "Mark Complete", complete_order_path(order), class: "button is-small is-primary #{'is-hidden' if order.completed?}", method: :put %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</section>

<script type="text/javascript" charset="utf-8">
  $(".toggle-modal").on('click', (e) => {
    e.stopPropagation();
    e.preventDefault();

    console.log(e);

    var order_id = e.target.getAttribute('aria-control');

    console.log('order-id: ', order_id);

    $('#star_' + order_id).raty({
      path: '/assets/raty-js/lib/images',
      scoreName: 'review[stars]',
      score: 1
    });

    // $('#star_' + order_id).raty('reload');

    $('#' + order_id).toggleClass('is-active');
  })
</script>

app/views/orders/selling_orders.html.erb
<section class="section">
  <div class="container">
    <p class="title">Manage Selling Orders</p>

    <table class="table is-fullwidth">
      <thead>
      <tr>
        <th>Date</th>
        <th>Buyer Name</th>
        <th>Title</th>
        <th>Due Date</th>
        <th>Amount</th>
        <th>Status</th>
      </tr>
      </thead>

      <tbody>
      <% if @orders.blank? %>
        <tr>
          <td colspan="6" class="has-text-centered"><h3>Nothing to show</h3></td>
        </tr>
      <% end %>

      <% @orders.each do |order| %>
        <tr>
          <td><%= order.created_at.strftime('%d %b %Y') %></td>
          <td><%= order.buyer_name %></td>
          <td>
            <%= link_to order.title, gig_path(order.gig) if order.gig.present? %>
            <%= link_to order.title, request_path(order.request) if order.request.present? %>
          </td>
          <td><%= order.due_date.strftime('%d %b %Y') %></td>
          <td>$<%= order.amount %></td>
          <td>
              <span class="tag <%= 'is-warning' if order.inprogress? %> <%= 'is-success' if order.completed? %>">
                <%= order.status.capitalize %>
              </span>

              <%= link_to "View", order_detail_path(order), class: "button is-small is-outlined" %>

          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/orders/show.html.erb
<section class="section" data-channel-subscribe="order" data-order-id="<%= @order.id %>">
  <div class="container">
    <div class="columns">

      <!-- LEFT SIDE -->
      <div class="column is-two-thirds">
        <p class="menu-label">
          Comments on your order
        </p>
        <hr>
        <div id="comment-list">
          <% @comments.each do |c| %>
            <%= render 'orders/comment', comment: c %>
          <% end %>
        </div>
        <hr>

        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <%= image_tag avatar_url(current_user), class: "is-rounded" %>
            </p>
          </figure>
          <div class="media-content">

            <%= form_with model: Comment.new, id: "new-comment" do |f| %>
              <%= f.hidden_field :order_id, value: @order.id %>
              <div class="field">
                <%= f.text_area :content, class: "textarea", placeholder: "Type your comment" %>
              </div>
              <div class="field is-pulled-right">
                <%= f.submit "Post Comment", class: "button is-primary" %>
              </div>
            <% end %>

          </div>
        </article>
      </div>

      <!-- RIGHT SIDE -->
      <div class="column">
        <div class="card">
          <div class="card-image">
            <figure class="image is-3by2">
              <!-- Gig / Request Cover here -->
              <%= image_tag gig_cover(@gig) if @gig %>
              <%= image_tag 'icon_default_image.png' if @request %>
            </figure>
          </div>
          <div class="card-content">
            <p>
              <strong><%= @order.title %></strong>
              <strong class="title is-4 is-pulled-right has-text-success">
                $<%= @order.amount %>
              </strong>
            </p>
            <br>
            <small>
              <p>Seller: <%= @order.seller_name %></p>
              <br>
              <p>Order: <%= @order.id %></p>
              <br>
              <p><%= @order.created_at.strftime("%d, %b %Y") %></p>
            </small>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>